sudo: required
dist: trusty
services:
  - docker
language: generic
python:
  - "2.7"
compiler:
  - gcc
notifications:

env:
  matrix:
    - ROS_DISTRO=melodic ROS_REPO=ros-shadow-fixed UPSTREAM_WORKSPACE=debian OS_NAME=ubuntu OS_CODE_NAME=bionic
   
  allow_failures:
    - env: ROS_DISTRO=melodic ROS_REPO=ros-shadow-fixed UPSTREAM_WORKSPACE=debian OS_NAME=debian OS_CODE_NAME=stretch
branches:
  only:
    - master
    - develop
    - takagon_delivery_challenge
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script: