sudo: required
cache:
- apt
language: generic

# ros distro
matrix:
  include:
  - name: "bionic melodic"
    dist: bionic
    env: ROS_DISTRO=melodic

# env
env:
  global:
    - ROS_CI_DESKTOP="`lsb_release -cs`"
    - CI_SOURCE_PATH=$(pwd)

before_install:
  # install ros_script
  - git clone https://github.com/ryuichiueda/ros_setup_scripts_Ubuntu18.04_desktop.git

  # ros_install
  - cd ros_setup_scripts_Ubuntu18.04_desktop
  - ./step0.bash && ./step1.bash
  - cd && source .bashrc


install:
  # make catkin_ws
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws/src
  - catkin_init_workspace
  - cd ~/catkin_ws
  - catkin_make
  - source devel/setup.bash
  - cd ~/catkin_ws/src
  - ln -s $CI_SOURCE_PATH .
  
script:
  # build
  - cd ~/catkin_ws
  - catkin_make